### ISSUE TITLE
Broken images

### ISSUE THREAD

**Issue by jaygarcia** [ModusCreateOrg/labs#17]
As of the time of this posting, there are some broken images.

![image](https://user-images.githubusercontent.com/180031/45044946-8d02cf80-b03f-11e8-94d7-955cbe4f3e27.png)

**Comment by grgur** [comment]
I can't seem to replicate this. Could you double check please? Could have been a temporary issue?

![image](https://user-images.githubusercontent.com/733074/45089938-17b20000-b10e-11e8-82d7-92c84de41ec3.png)

**Comment by jaygarcia** [comment]
I suspect the images being served by Github sometimes get borked. I get the same on the github and black arrows from time to time. :(
