### ISSUE TITLE
Feature: Project detail page

### ISSUE THREAD

**Issue by grgur** [ModusCreateOrg/labs#20]
Show project detail (landing) page. Each project should have a custom-defined route URL.
Use existing data.

Mockup: https://moduscreate.invisionapp.com/d/main/#/console/14780151/319006914/preview

![image](https://user-images.githubusercontent.com/733074/46406537-29d28e80-c70c-11e8-980d-a7a871b00a5b.png)

**Comment by matiasfh** [comment]
The data required to create the page (text, description, titles, images) will be available in src/data/projects/*.json ?

**Comment by grgur** [comment]
yes sir, it's all there. You may need to add `route`

**Comment by grgur** [comment]
@nikhilknoldus working on this atm

**Comment by grgur** [comment]
Completed
