### ISSUE TITLE
Links should have a “Modus red” (#ff5c5d) hover state.

### ISSUE THREAD

**Issue by alin-baicoci** [ModusCreateOrg/labs#38]
Given that I'm on a Detail page of a project
When I hover over a link on that page
Then I want to see the “Modus red” (#ff5c5d) hover state.
eg: link present under Ionic-Vue description

**Comment by rmarquez-modus** [comment]
@alin-baicoci @grgur 
What should happen to the Social Networks links at the bottom(where the team members are) ? should they have the same behavior ?

I ask this because those links act as buttons and they back `.svg` images which will not look good if we apply the same styles.

**Comment by alin-baicoci** [comment]
Hey @rmarquez-modus. No changes to the "social networks buttons", for now.

**Comment by grgur** [comment]
Thanks for fixing this!
