### ISSUE TITLE
Cookie acceptance footer disappears on scroll

### ISSUE THREAD

**Issue by theneverstill** [ModusCreateOrg/labs#4]
Steps to repeat:

1. Go to: https://labs.moduscreate.com/
2. Observe cookie acceptance footer
3. Scroll down

Expected:
- Cookie acceptance footer remains until user clicks button accepts cookies

Actual:
- Cookie acceptance footer disappears

**Comment by grgur** [comment]
@theneverstill thank you for this report. I reviewed our Cookiebot settings and here's what I found.

Cookie acceptance messages goes as this:

> We use cookies to personalize content and ads, to provide social media features and to analyze our traffic. We also share information about your use of our site with our social media, advertising and analytics partners who may combine it with other information that you’ve provided to them or that they’ve collected from your use of their services. You consent to our cookies if you continue to use our website.

As such, Cookiebot treats scroll as __usage__, thus acceptance is granted. 

This behavior can be turned off, but I like at as it's less obtrusive than forcing the popup.
