### ISSUE TITLE
Cookie acceptance footer doesn't show on refresh

### ISSUE THREAD

**Issue by theneverstill** [ModusCreateOrg/labs#5]
The cookie acceptance footer does not reappear on page refresh (when not accepted).

Steps to repeat:

1. Go to: https://labs.moduscreate.com/
2. Observe cookie acceptance footer
3. Refresh the page (do NOT click the 'OK' button on the cookie acceptance footer)

Expected:

- Cookie acceptance footer reappears on page reload

Actual:

- Cookie acceptance footer does not reappear

**Comment by grgur** [comment]
Similar to #4, usage counts as acceptance :)

Thank you @theneverstill
