### ISSUE TITLE
Service worker errors in console

### ISSUE THREAD

**Issue by theneverstill** [ModusCreateOrg/labs#6]
There are service worker errors in the console on page loads after the service worker has been registered.

Steps to repeat:

1. Go to: https://labs.moduscreate.com/
2. Observe in console: 
`installingWorker`
`Content is now available offline!`
3. Refresh the page

Expected:

- No service worker errors in console

Actual:

- Observe in console:

`
sw.js:279 Uncaught (in promise) Error: Both cache and network failed: "TypeError: Failed to fetch", "No result returned"
    at u (sw.js:279)
    at f (sw.js:279)
`

**Comment by grgur** [comment]
Fixed with CSP fixes
