### ISSUE TITLE
Fix deployments

### ISSUE THREAD

**Issue by rodriguezmanu** [ModusCreateOrg/labs#85]
Currenly deployments is not working on AWS and netlify

**Comment by rodriguezmanu** [comment]
` node-sass@4.14.1 postinstall /codebuild/output/src471002151/src/github.com/ModusCreateOrg/labs/node_modules/node-sass
76	> node scripts/build.js
77	
78	Binary found at /codebuild/output/src471002151/src/github.com/ModusCreateOrg/labs/node_modules/node-sass/vendor/linux-x64-64/binding.node
79	Testing binary
80	Binary is fine
81	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
82	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
83	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
84	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
85	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
86	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
87	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/chokidar/node_modules/fsevents):
88	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
89	
90	added 2216 packages in 26.361s
91	
92	[Container] 2021/06/10 18:59:21 Phase complete: INSTALL State: SUCCEEDED
93	[Container] 2021/06/10 18:59:21 Phase context status code:  Message: 
94	[Container] 2021/06/10 18:59:21 Entering phase PRE_BUILD
95	[Container] 2021/06/10 18:59:21 Phase complete: PRE_BUILD State: SUCCEEDED
96	[Container] 2021/06/10 18:59:21 Phase context status code:  Message: 
97	[Container] 2021/06/10 18:59:21 Entering phase BUILD
98	[Container] 2021/06/10 18:59:21 Running command $BUILD_COMMANDS
99	
100	> @modus/labs@2.0.0 build /codebuild/output/src471002151/src/github.com/ModusCreateOrg/labs
101	> gatsby build
102	
103	error Gatsby requires Node.js 10.13.0 or higher (you have v10.1.0).
104	Upgrade Node to the latest stable release: https://gatsby.dev/upgrading-node-js
105	npm ERR! code ELIFECYCLE
106	npm ERR! errno 1
107	npm ERR! @modus/labs@2.0.0 build: `gatsby build`
108	npm ERR! Exit status 1
109	npm ERR! 
110	npm ERR! Failed at the @modus/labs@2.0.0 build script.
111	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`


According logs aws, we have to update node version on aws (error Gatsby requires Node.js 10.13.0 or higher (you have v10.1.0)

Currently I do not have privilegies to add this one.

**Comment by rodriguezmanu** [comment]
![Screen Shot 2021-06-11 at 18 05 25](https://user-images.githubusercontent.com/1910226/121748725-d5e4ee00-cadf-11eb-8ab8-0f2c44d377ff.png)

**Comment by crissoca** [comment]
Looping @jaygarcia and @grgur 
Can we get someone with the right access to take a look at this?

**Comment by rodriguezmanu** [comment]
@kelchm is on it also

**Comment by kelchm** [comment]
Hey all -- sorry for there delay on this. I'm digging into it now.

**Comment by kelchm** [comment]
@rodriguezmanu @crissoca this should now be resolved -- I've moved us to a current `aws/codebuild/amazonlinux2-x86_64-standard:3.0` image and specific node 10 in the build spec.

**Comment by rodriguezmanu** [comment]
Awesome, thanks @kelchm

**Comment by crissoca** [comment]
So cool! Thanks.

**Comment by grgur** [comment]
Thank you @kelchm 

Is this resolved now?
