### ISSUE TITLE
Readme file should describe publishing pipeline

### ISSUE THREAD

**Issue by obscurerichard** [ModusCreateOrg/labs#9]
It's not clear how to test this locally or this gets published. Is there CI involved? Does some service pull it? DNS suggests Netlify is involved:
```
$ host labs.moduscreate.com
labs.moduscreate.com is an alias for moduslabs.netlify.com.
moduslabs.netlify.com has address 206.81.1.198
```

**Comment by grgur** [comment]
Updated in #15 

Thanks for reporting @obscurerichard
