### ISSUE TITLE
Please remove background image on footer

### ISSUE THREAD

**Issue by jaygarcia** [ModusCreateOrg/labs#93]
This footer image is added twice in the codebase. 

![image](https://user-images.githubusercontent.com/180031/123296764-ef753500-d4e4-11eb-8660-2299f2ac717a.png)

Looks like it's styles applied to this Section element.
![image](https://user-images.githubusercontent.com/180031/123297032-2ea38600-d4e5-11eb-9ba4-20ce55afcd76.png)

These background styles:
![image](https://user-images.githubusercontent.com/180031/123297074-3a8f4800-d4e5-11eb-9501-1b8a1e2358e1.png)

**Comment by rodriguezmanu** [comment]
I think this project is with mobile first styling so first one is for desktop(with media query) and second one is for mobile (no media query)

**Comment by jaygarcia** [comment]
Is it easy to remove that image? :)

**Comment by rodriguezmanu** [comment]
Are 2 different images for desktop and mobile
![Screen Shot 2021-06-24 at 15 23 06](https://user-images.githubusercontent.com/1910226/123337248-4f87cd80-d51d-11eb-8746-818143c8cbb9.png)

![Screen Shot 2021-06-24 at 15 34 22](https://user-images.githubusercontent.com/1910226/123337223-472f9280-d51d-11eb-8202-7500b7cd4eb3.png)

**Comment by jaygarcia** [comment]
Gotcha!! let's please remove both :D
